### ISSUE TITLE
returned a non-zero code : 127

### ISSUE THREAD

**Issue by linkcrux** [rhopman/docker-oracle-12c#2]
Got the below error when I ran : 

> docker build -t oracle12c .
> 
> Step 22 : RUN /home/oracle/bin/postinstall.sh
>  ---> Running in b33f3e79be06
> /home/oracle/bin/postinstall.sh: line 1: /opt/oraInventory/orainstRoot.sh: No such file or directory
> /home/oracle/bin/postinstall.sh: line 2: /opt/oracle/product/12.1.0.2/dbhome_1/root.sh: No such file or directory
> The command '/bin/sh -c /home/oracle/bin/postinstall.sh' returned a non-zero code: 127

**Comment by linkcrux** [comment]
am i missing something ?

**Comment by rmazum** [comment]
I faced the same issue. Can anyone help please ?

Step 21/27 : RUN /home/oracle/bin/postinstall.sh
 ---> Running in 544feb215494
/home/oracle/bin/postinstall.sh: line 1: /opt/oraInventory/orainstRoot.sh: No such file or directory
/home/oracle/bin/postinstall.sh: line 2: /opt/oracle/product/12.1.0.2/dbhome_1/root.sh: No such file or directory
The command '/bin/sh -c /home/oracle/bin/postinstall.sh' returned a non-zero code: 127

**Comment by YevgenK** [comment]
Do you use windows? I had the same issue. Try to change the line ending for .sh and Dockerfile files to LF.

**Comment by rhopman** [comment]
First, make sure to check for error messages in earlier steps. The fact that `/opt/oraInventory/orainstRoot.sh` is not found, might indicate a failure in `/home/oracle/bin/install.sh`. Unfortunately, this script does not return a non-zero exit code when it fails, so it's easy to miss.

I suspect the second error might be due to a mismatch between the Oracle version you downloaded, and the path in `postinstall.sh`.

I made some adjustments to make everything a bit clearer and more robust. I'm closing the issue for now; please open a new issue if these problems persist and you feel they are not explained by what I mentioned here.
